### PR TITLE
feat: add react-actioncable-provider package and generate todos channel

### PR DESCRIPTION
**Pull request by LeeRenJie**

### CODE REVIEW

**Review by tlkiong — COMMENTED** [review]
WHat is the use of redis gem here?

**Comment by LeeRenJie** [comment]
> WHat is the use of redis gem here?

was following an article, realized it is not needed now unless i push it to production

**Comment by tlkiong** [comment]
so, what is the use of redis in production?

**Comment by LeeRenJie** [comment]
> so, what is the use of Redis in production?

Redis is an in-memory data structure store used to help build high-performance and scalable web applications. It can be used as a database, cache system, or message-queue broker. 

For action cable, it uses Redis as a data store for transient data, syncing content across instances of the application.

Action Cable uses Redis to send and receive messages over the channel. So, when we tell our Action Cable server to `#broadcast` to `'messages'`, we were actually saying "send new messages to the 'messages' channel maintained by Redis."

At the same time, the `#subscribed` method of our Messages Channel is really streaming messages sent over the `'messages'` channel maintained by Redis.
Thus, Redis acts as a data store and ensures that messages will remain in sync across instances of our application.

Action Cable will look for the Redis configuration in `Rails.root.join('config/cable.yml')`. When we generated our new Rails 6 app, we also generated a file, config/cable.yml, that looks like this:

```ruby
development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: websocket_production
```

Here, we are specifying an adapter and a URL for each environment. When deployed into production, the URL can be changed accordingly.
  

References: 
- [What is redis?](https://davidmles.medium.com/what-is-redis-a-gentle-introduction-using-ruby-ba4c4055b84b)
- [redis-rb Repository](https://github.com/redis/redis-rb)
- [Real-Time Rails: Implementing WebSockets in Rails 5 with Action Cable](https://blog.heroku.com/real_time_rails_implementing_websockets_in_rails_5_with_action_cable)

**Review by tlkiong — APPROVED** [review]
Good.
Note that redis is a db. It don't need to run action cable. But action cable needs it or something similar. You can use redis for toehr things

**Pull request merged**
