### PR TITLE
feat(user model): user has many children association

### PR DESCRIPTION
**Pull request by LeeRenJie**
user model
```ruby
class User < ApplicationRecord
  class User < ApplicationRecord
  has_many :children, -> (user) { unscope(:where).where("father_id = :id OR mother_id = :id", id: user.id) }, class_name: "User"
  belongs_to :mother, class_name: "User", optional: true
  belongs_to :father, class_name: "User", optional: true
end
  # If want user.parent then add
  belongs_to :parent, class_name: "User", optional: true
end
```

Output for `user.children`:
image

### CODE REVIEW

**Review by tlkiong — CHANGES_REQUESTED** [review]
huh?
Why remove mother father all. I still want those :(

**Comment by LeeRenJie** [comment]
> huh?
> Why remove mother father all. I still want those :(

okok I add as comment

**Comment by tlkiong** [comment]
Wat do you mean add as comment.
The requirement is to do grandchildren.
I didn't say remove mother father, grandmother, grandfather.
.....

**Review by tlkiong — CHANGES_REQUESTED** [review]
remove all `grandchildren` if its not part of this PR

**Review by tlkiong — CHANGES_REQUESTED** [review]
please remove *ALL* mention of grandchildren in this PR. Including PR descriptions

**Review by tlkiong — APPROVED** [review]

**Pull request merged**
